name: sample_architecture
description: A sample architecture

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  base_codecs: ^1.0.1
  bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  data_queue: ^1.0.2
  de_log: ^1.0.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  hive: ^2.0.4
  intl: ^0.17.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  generate: true
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
